sudo: required
language: php
notifications:
  on_success: never
  on_failure: change
addons:
  artifacts: true
php:
- 5.6
env:
  global:
  - secure: bXzEwcSIL+W2A7mBR901AxhYappjBYVs4pO9tbZvEBPZq/nx7f1qEBZuuDuTCCPfnVi+fHOriQ2mK9fAo1LhMpZlahdkMNnSb8WEtf1YCLKMLG/bozgqxwDiOkw4kinltEp69rO95UWK/eY/E9wlZA90Z5XY1BHQ40+etNLVGAZlXoI60SFOTodCzICIx1J3norcKn8uDDLwSgg1PCL5BNOTQ7MhXL/cduw7vC+d9nvM5OaXGOGOi7pwtqjfR9x680jjGGZO+7j6+iBD6w2hRNLyo1LnUtjItXOf3jjkdKyfZONu6hbAyHC+W8eSx4MByyLEAM9vO2lD5zLafd2VGOcpNBty3ops3wP8FgN/KIl/3u9wfUKQIPCfINNnAb26cGnNcfN96Z5Wgfv/pQJutHJAdPo8Rlvw22FTT08PzPOY00n+AtGFo/Tcwlln/W7TZl9i4OGVinXBdpukdZ8Iz359dFrBn5Wrb4UOx01w6vQecsvLCWZregUEycAw6tGRuHWtVzfGASZIm1cTH5kZnLuX2s1cDJtUeR6DY2I6ET19BxU56bAs4m2N66mjPbZAm3ltmZwcgpKyi0p0zfZx/2z+UFzk7ZOmRvY92ghU6kzMJLUR8oojT36InQih3i9otpYF2tiQF3bzVM2ChXMJ9YGFz+wTiBYE6P2aYIK5xGs=
  - secure: Cq6wCO4jAlccfS6pR26ukcJ1jTKYu3pR/6c6pyx6/0gnDpY8fP/ACq2Q7RsBPLjJ9K1u2EqJR1PbKUntKPdeyDv9bMDW6Gyg5aQh1lJ0Sf5Daq31X0VuqqbO1Y3pZ2gXMrYV6sifVs83VkBNpKeqg2hN6WcNo3bfzG9cdVaiG8yoqkKYubW5hdh2zmh7Re8uNGnzca5g6f5FerQlBLBW8iwptFUWSjv9eGdkU1k2Gmg54fbGA+DP7gtzGU8uGeqVuS4fgE+nIAcLXaCc5orrSMjOxvhafG9vptHo1Js25rKc4YIu7ifpLfSAImeOSN1+z7GiNLEJ4UNFPC/NwncUZyhUUebg//AuDwFyydKrwooOqFFM7aCRqe2xim/Bs7pCZ8CgO8IlWZig5Uvv7RXPqp7qCOH2QE9hl3zLncaGE8ryzOtWVEui/7loIlsZ/4NzdEqUgk1v8XehGD+92BVf5aO88hFMvc0CP7QG9e06dRKKMr372lG574z/2oBhia01XAuPiMnqX/rUY/UuKNMbTs82vseFZahRyxBQ6X0mphSBEhHDLyszFuiwXMWOxm397dqQpm+fgYKJuH31movfStttmXdNBDrhG0GuMUW+tySukiB8NkSFYm8NJP/6YmOybZ2IEjdjWkocszH/fqW8PhIzX9Glez9Vayy8wf2c+/Q=
  - ARTIFACTS_BUCKET=travis-test-cremins
  - ARTIFACTS_REGION=Oregon
  matrix:
  - WP_VERSION=latest WP_MULTISITE=0
before_script:
- export WP_VERSION=master
- export WP_DEVELOP_DIR=/tmp/wordpress
- export WP_CORE_DIR=/tmp/wordpress/src
- export WP_CEPT_SERVER='127.0.0.1:8888'
- source travis.sh
- install-wordpress
- php -S "$WP_CEPT_SERVER" -t "$WP_CORE_DIR" >/dev/null 2>&1 &
- phantomjs --webdriver=4444 >/dev/null 2>&1 &
- composer install --prefer-source
script:
- vendor/bin/codecept run --html
after_success: |
  if [ "$TRAVIS_BRANCH" == "development" ]; then
    repo_temp=$(mktemp -d)
    git clone "https://github.com/dCremins/add-ons" "$repo_temp"
    cd "$repo_temp"
    printf 'Checking out Master'
    git checkout master
    printf 'Merging %s\n' "$TRAVIS_COMMIT" >&2
    git merge --ff-only "$TRAVIS_COMMIT"
    printf 'Pushing to Add-Ons'
    git push "https://$DEPLOY_KEY@github.com/dCremins/add-ons" \
        "master" >/dev/null 2>&1
  fi
deploy:
  provider: releases
  api_key:
    secure: UmSoS+WXwfBs3IB4jKiJrA1myVrBREFnF09czkLyTCG92SmpUZx4/eu4NmTEX/Em4MPedgMywvdBT73i2OywDVspRcgfn1+YDXmoiQyM5K3+dQJP8g549ZTJkjkWgXSvHyYsWxBMipDuZxoHAgIs9DhUC443XmuZT/VG99uD0edGU4DqEDVnb694EnkILQDjyqpgMYdcXLX+otuULBecsOWEoLpIX9CSmkDa1aCQdBz31zfnsfNhqZBW44CikXMYMRLyr+X4ZfN0o/UefSufM8oZn404wgArbThXIgRV50PuZSzAPGXDdf/dX28EwDspXOlOUjCPHj/59l9J1JZIxDFCGA6og7oaUhYTnjEhiYPRmzlp1clzvjXHjj6kSeH2vvT3tb/CP5QZuutttFRkWCC4/Dni8keVqX4TZSs63nL8pgWcewy2IngoZ5FdRJsQ+UVT868IsSNST1rCXlpJ4wPoyzvAor4cB6kidGO2JmTw0LzlpdSBVSAf96gt21SCu8tvwuTKlNLnyJOQF8C8catSDy/Bg0742GS4/qgpsgZQyD8NdE1sF1A4mVSA0jWXOlI86UGDmvFpIxEeU54712wsNicaFf3NXl2W5dJnVzuZRPoEmlQBVbNOUoXfm+aAfbYnh1VWgYY56FvXjWJJQgSWb+iWS0pGOMoPU4Qhh5g=
  file:
  - "./tests/_output/report.html"
  skip_cleanup: true
  on:
    tags: true
