sudo: false
language: php

notifications:
  on_success: never
  on_failure: change

php:
  - 5.6

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=3.7 WP_MULTISITE=0
  - WP_VERSION=4.7.2 WP_MULTISITE=0

install:
  - composer self-update
  - composer install

matrix:
  include:
      env: WP_VERSION=latest WP_MULTISITE=1

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.0" ]]; then
      composer global require "phpunit/phpunit=5.6.*"
    else
      composer global require "phpunit/phpunit=4.8.*"
    fi
  - |
    composer global require wp-coding-standards/wpcs
    phpcs --config-set installed_paths $HOME/.composer/vendor/wp-coding-standards/wpcs
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - wget http://selenium-release.storage.googleapis.com/2.42/selenium-server-standalone-2.42.2.jar
  - java -jar selenium-server-standalone-2.42.2.jar -port 4444 &
  - php -S localhost:8000 -t tests/data/app &
  - curl -s http://getcomposer.org/installer | php
  - composer install -n --prefer-source
  - "mysql -e 'create database codeception_test;'"
  - psql -c 'create database codeception_test;' -U postgres

script:
  - php vendor/codeception/codeception/codecept run

after_success: |
  if [ "$TRAVIS_BRANCH" == "development" ]; then
    repo_temp=$(mktemp -d)
    git clone "https://github.com/dCremins/add-ons" "$repo_temp"
    cd "$repo_temp"
    printf 'Checking out Master'
    git checkout master
    printf 'Merging %s\n' "$TRAVIS_COMMIT" >&2
    git merge --ff-only "$TRAVIS_COMMIT"
    printf 'Pushing to Add-Ons'
    git push "https://$DEPLOY_KEY@github.com/dCremins/add-ons" \
        "master" >/dev/null 2>&1
  fi
