sudo: false
language: php
notifications:
  on_success: never
  on_failure: change
php:
- 5.6
env:
- WP_VERSION=latest WP_MULTISITE=0
before_script:
- export WP_VERSION=master
- export WP_DEVELOP_DIR=/tmp/wordpress
- export WP_CORE_DIR=/tmp/wordpress/src
- export WP_CEPT_SERVER='127.0.0.1:8888'
- source travis.sh
- install-wordpress
- php -S "$WP_CEPT_SERVER" -t "$WP_CORE_DIR" >/dev/null 2>&1 &
- phantomjs --webdriver=4444 >/dev/null 2>&1 &
- composer install --prefer-source
script:
- vendor/bin/codecept run --html
- make dist
# composer test
after_success: |
  if [ "$TRAVIS_BRANCH" == "development" ]; then
    repo_temp=$(mktemp -d)
    git clone "https://github.com/dCremins/add-ons" "$repo_temp"
    cd "$repo_temp"
    printf 'Checking out Master'
    git checkout master
    printf 'Merging %s\n' "$TRAVIS_COMMIT" >&2
    git merge --ff-only "$TRAVIS_COMMIT"
    printf 'Pushing to Add-Ons'
    git push "https://$DEPLOY_KEY@github.com/dCremins/add-ons" \
        "master" >/dev/null 2>&1
  fi
deploy:
  provider: releases
  api_key:
    secure: UmSoS+WXwfBs3IB4jKiJrA1myVrBREFnF09czkLyTCG92SmpUZx4/eu4NmTEX/Em4MPedgMywvdBT73i2OywDVspRcgfn1+YDXmoiQyM5K3+dQJP8g549ZTJkjkWgXSvHyYsWxBMipDuZxoHAgIs9DhUC443XmuZT/VG99uD0edGU4DqEDVnb694EnkILQDjyqpgMYdcXLX+otuULBecsOWEoLpIX9CSmkDa1aCQdBz31zfnsfNhqZBW44CikXMYMRLyr+X4ZfN0o/UefSufM8oZn404wgArbThXIgRV50PuZSzAPGXDdf/dX28EwDspXOlOUjCPHj/59l9J1JZIxDFCGA6og7oaUhYTnjEhiYPRmzlp1clzvjXHjj6kSeH2vvT3tb/CP5QZuutttFRkWCC4/Dni8keVqX4TZSs63nL8pgWcewy2IngoZ5FdRJsQ+UVT868IsSNST1rCXlpJ4wPoyzvAor4cB6kidGO2JmTw0LzlpdSBVSAf96gt21SCu8tvwuTKlNLnyJOQF8C8catSDy/Bg0742GS4/qgpsgZQyD8NdE1sF1A4mVSA0jWXOlI86UGDmvFpIxEeU54712wsNicaFf3NXl2W5dJnVzuZRPoEmlQBVbNOUoXfm+aAfbYnh1VWgYY56FvXjWJJQgSWb+iWS0pGOMoPU4Qhh5g=
  file:
    - './tests/_output/report.html'
    - 'release.zip'
  skip_cleanup: true
  on:
    repo: dCremins/proceedings
    branch: 1-archive
    tags: true
